name: CI Action

on:
  push:
    branches:
      - main

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install additional dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./project/requirements.txt

      # Run test pipeline
      - name: Run test pipeline
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
